In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold

In [2]:
df = pd.read_csv("../data/BBBC021/BBBC021_labels.csv")
df

,Unnamed: 0,meta_path,moa_Actin_disruptors,moa_Aurora_kinase_inhibitors,moa_Cholesterol-lowering,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [3]:
df["fold"] = -1
df

,Unnamed: 0,meta_path,moa_Actin_disruptors,moa_Aurora_kinase_inhibitors,moa_Cholesterol-lowering,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis,fold
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1

In [ ]:
# 2. Gather multi-label columns
moa_cols = [c for c in df.columns if c.startswith("moa_")]
y = df[moa_cols].astype(int)

# 3. Create a new string label representing combinations
df["combo"] = y.apply(lambda row: "_".join(row.astype(str)), axis=1)

# 4. Add fold column
df["fold"] = -1
skf = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

# 5. Assign folds based on combo
for fold, (_, val_idx) in enumerate(skf.split(df, df["combo"])):
    df.loc[val_idx, "fold"] = fold

# 6. Cleanup if needed
df = df.drop(columns=["combo"])

In [7]:
df

,Unnamed: 0,meta_path,moa_Actin_disruptors,moa_Aurora_kinase_inhibitors,moa_Cholesterol-lowering,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis,fold
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,2
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,3
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,2
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,1
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,0
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,2
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,3
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,0
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,0

In [9]:
df.to_csv("../data/BBBC021/BBBC021_labels_folded.csv")