In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("../data/BBBC021/BBBC021_dataset_complete.csv")
data

,Unnamed: 0,meta_path,meta_bbox_minr,meta_bbox_minc,meta_bbox_maxr,meta_bbox_maxc,meta_regions_DAPI,meta_regions_actin,meta_regions_tubulin,feat_area_combined,...,feat_combined_glcm_mean_ASM_5_tubulin,feat_combined_glcm_std_ASM_3_tubulin,feat_combined_glcm_std_ASM_5_tubulin,feat_combined_sobel_mean_tubulin,feat_combined_sobel_std_tubulin,feat_combined_sobel_max_tubulin,feat_combined_sobel_min_tubulin,meta_filename,Image_Metadata_Compound,Image_Metadata_Concentration
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,8.0,722.0,64.0,805.0,1.0,1.0,1.0,0.042649,...,0.019653,0.000285,0.004497,0.091486,0.057134,0.088128,0.016896,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,56.0,587.0,147.0,636.0,1.0,1.0,1.0,0.038207,...,0.042773,0.008115,0.005507,0.031282,0.022190,0.028979,0.003125,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,139.0,1010.0,197.0,1024.0,0.0,1.0,1.0,0.008588,...,0.026532,0.004049,0.012264,0.117778,0.061958,0.057363,0.010489,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,143.0,670.0,206.0,773.0,1.0,1.0,1.0,0.052249,...,0.026993,0.003595,0.000138,0.064662,0.040589,0.080440,0.018566,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,153.0,0.0,228.0,60.0,1.0,1.0,1.0,0.044052,...,0.029941,0.010810,0.002365,0.047504,0.029420,0.042346,0.012346,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1217.0,666.0,1280.0,761.0,1.0,1.0,1.0,0.037973,...,0.069967,0.003801,0.007824,0.073344,0.059778,0.076795,0.003272,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1242.0,77.0,1280.0,153.0,1.0,1.0,1.0,0.021345,...,0.031972,0.030926,0.021669,0.168554,0.117598,0.188737,0.056019,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1251.0,759.0,1280.0,805.0,1.0,1.0,1.0,0.010836,...,0.036170,0.013998,0.007219,0.165575,0.138171,0.137055,0.056968,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1262.0,865.0,1280.0,908.0,0.0,1.0,1.0,0.006055,...,0.019146,0.017737,0.020251,0.155521,0.077499,0.095857,0.106528,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1265.0,547.0,1280.0,590.0,1.0,1.0,1.0,0.006328,...,0.061544,0.038937,0.070802,0.109683,0.105302,0.162887,0.017610,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3

In [3]:
labels = pd.read_csv("../data/BBBC021/BBBC021_labels.csv")
labels

,Unnamed: 0,meta_path,moa_Actin_disruptors,moa_Aurora_kinase_inhibitors,moa_Cholesterol-lowering,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [4]:
train_cal_val_df, test_df = train_test_split(data, test_size=0.2, random_state=42)

In [5]:
train_cal_df, val_df = train_test_split(
    train_cal_val_df, test_size=0.25, random_state=42
)

In [6]:
train_df, cal_df = train_test_split(train_cal_df, test_size=0.20, random_state=42)

In [7]:
train_df["split"] = "train"
val_df["split"] = "val"
test_df["split"] = "test"
cal_df["split"] = "cal"

In [8]:
data_with_split = pd.concat([train_df, val_df, test_df, cal_df]).reset_index(drop=True)

In [9]:
data_with_split = data_with_split.sort_values(
    by="Unnamed: 0", ascending=True, ignore_index=True
)

In [10]:
data_with_split

,Unnamed: 0,meta_path,meta_bbox_minr,meta_bbox_minc,meta_bbox_maxr,meta_bbox_maxc,meta_regions_DAPI,meta_regions_actin,meta_regions_tubulin,feat_area_combined,...,feat_combined_glcm_std_ASM_3_tubulin,feat_combined_glcm_std_ASM_5_tubulin,feat_combined_sobel_mean_tubulin,feat_combined_sobel_std_tubulin,feat_combined_sobel_max_tubulin,feat_combined_sobel_min_tubulin,meta_filename,Image_Metadata_Compound,Image_Metadata_Concentration,split
0,0,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,8.0,722.0,64.0,805.0,1.0,1.0,1.0,0.042649,...,0.000285,0.004497,0.091486,0.057134,0.088128,0.016896,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3,val
1,1,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,56.0,587.0,147.0,636.0,1.0,1.0,1.0,0.038207,...,0.008115,0.005507,0.031282,0.022190,0.028979,0.003125,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3,cal
2,2,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,139.0,1010.0,197.0,1024.0,0.0,1.0,1.0,0.008588,...,0.004049,0.012264,0.117778,0.061958,0.057363,0.010489,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3,test
3,3,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,143.0,670.0,206.0,773.0,1.0,1.0,1.0,0.052249,...,0.003595,0.000138,0.064662,0.040589,0.080440,0.018566,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3,val
4,4,Week5_28901/Week5_130707_F02_s3_w185DF55C5-FB1...,153.0,0.0,228.0,60.0,1.0,1.0,1.0,0.044052,...,0.010810,0.002365,0.047504,0.029420,0.042346,0.012346,Week5_130707_F02_s3_w185DF55C5-FB17-4116-9A86-...,taxol,0.3,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1217.0,666.0,1280.0,761.0,1.0,1.0,1.0,0.037973,...,0.003801,0.007824,0.073344,0.059778,0.076795,0.003272,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3,test
512631,512631,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1242.0,77.0,1280.0,153.0,1.0,1.0,1.0,0.021345,...,0.030926,0.021669,0.168554,0.117598,0.188737,0.056019,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3,train
512632,512632,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1251.0,759.0,1280.0,805.0,1.0,1.0,1.0,0.010836,...,0.013998,0.007219,0.165575,0.138171,0.137055,0.056968,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3,cal
512633,512633,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1262.0,865.0,1280.0,908.0,0.0,1.0,1.0,0.006055,...,0.017737,0.020251,0.155521,0.077499,0.095857,0.106528,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3,val
512634,512634,Week5_28901/Week5_130707_F02_s2_w111C4D15B-50B...,1265.0,547.0,1280.0,590.0,1.0,1.0,1.0,0.006328,...,0.038937,0.070802,0.109683,0.105302,0.162887,0.017610,Week5_130707_F02_s2_w111C4D15B-50BA-49B6-A5B7-...,taxol,0.3,test

In [11]:
# data_with_split.to_csv('../data/BBBC021/BBBC021_dataset_complete_one_fold.csv', index=False)

In [12]:
feature_columns = [
    col
    for col in data_with_split.columns
    if col.startswith("feat_") or col == "Unnamed: 0" or col == "split"
]
feature_columns

['Unnamed: 0',
 'feat_area_combined',
 'feat_convex_area_combined',
 'feat_eccentricity_combined',
 'feat_equivalent_diameter_combined',
 'feat_euler_number_combined',
 'feat_feret_diameter_max_combined',
 'feat_filled_area_combined',
 'feat_major_axis_length_combined',
 'feat_minor_axis_length_combined',
 'feat_orientation_combined',
 'feat_perimeter_combined',
 'feat_perimeter_crofton_combined',
 'feat_solidity_combined',
 'feat_extent_combined',
 'feat_inertia_tensor-0-0_combined',
 'feat_inertia_tensor-0-1_combined',
 'feat_inertia_tensor-1-0_combined',
 'feat_inertia_tensor-1-1_combined',
 'feat_inertia_tensor_eigvals-0_combined',
 'feat_inertia_tensor_eigvals-1_combined',
 'feat_moments-0-0_combined',
 'feat_moments-0-1_combined',
 'feat_moments-0-2_combined',
 'feat_moments-0-3_combined',
 'feat_moments-1-0_combined',
 'feat_moments-1-1_combined',
 'feat_moments-1-2_combined',
 'feat_moments-1-3_combined',
 'feat_moments-2-0_combined',
 'feat_moments-2-1_combined',
 'feat_moments-2-2_combined',
 'feat_moments-2-3_combined',
 'feat_moments-3-0_combined',
 'feat_moments-3-1_combined',
 'feat_moments-3-2_combined',
 'feat_moments-3-3_combined',
 'feat_moments_central-0-0_combined',
 'feat_moments_central-0-1_combined',
 'feat_moments_central-0-2_combined',
 'feat_moments_central-0-3_combined',
 'feat_moments_central-1-0_combined',
 'feat_moments_central-1-1_combined',
 'feat_moments_central-1-2_combined',
 'feat_moments_central-1-3_combined',
 'feat_moments_central-2-0_combined',
 'feat_moments_central-2-1_combined',
 'feat_moments_central-2-2_combined',
 'feat_moments_central-2-3_combined',
 'feat_moments_central-3-0_combined',
 'feat_moments_central-3-1_combined',
 'feat_moments_central-3-2_combined',
 'feat_moments_central-3-3_combined',
 'feat_moments_hu-0_combined',
 'feat_moments_hu-1_combined',
 'feat_moments_hu-2_combined',
 'feat_moments_hu-3_combined',
 'feat_moments_hu-4_combined',
 'feat_moments_hu-5_combined',
 'feat_moments_hu-6_combined',
 'feat_area_DAPI',
 'feat_convex_area_DAPI',
 'feat_eccentricity_DAPI',
 'feat_equivalent_diameter_DAPI',
 'feat_euler_number_DAPI',
 'feat_feret_diameter_max_DAPI',
 'feat_filled_area_DAPI',
 'feat_major_axis_length_DAPI',
 'feat_minor_axis_length_DAPI',
 'feat_orientation_DAPI',
 'feat_perimeter_DAPI',
 'feat_perimeter_crofton_DAPI',
 'feat_solidity_DAPI',
 'feat_extent_DAPI',
 'feat_inertia_tensor-0-0_DAPI',
 'feat_inertia_tensor-0-1_DAPI',
 'feat_inertia_tensor-1-0_DAPI',
 'feat_inertia_tensor-1-1_DAPI',
 'feat_inertia_tensor_eigvals-0_DAPI',
 'feat_inertia_tensor_eigvals-1_DAPI',
 'feat_moments-0-0_DAPI',
 'feat_moments-0-1_DAPI',
 'feat_moments-0-2_DAPI',
 'feat_moments-0-3_DAPI',
 'feat_moments-1-0_DAPI',
 'feat_moments-1-1_DAPI',
 'feat_moments-1-2_DAPI',
 'feat_moments-1-3_DAPI',
 'feat_moments-2-0_DAPI',
 'feat_moments-2-1_DAPI',
 'feat_moments-2-2_DAPI',
 'feat_moments-2-3_DAPI',
 'feat_moments-3-0_DAPI',
 'feat_moments-3-1_DAPI',
 'feat_moments-3-2_DAPI',
 'feat_moments-3-3_DAPI',
 'feat_moments_central-0-0_DAPI',
 'feat_moments_central-0-1_DAPI',
 'feat_moments_central-0-2_DAPI',
 'feat_moments_central-0-3_DAPI',
 'feat_moments_central-1-0_DAPI',
 'feat_moments_central-1-1_DAPI',
 'feat_moments_central-1-2_DAPI',
 'feat_moments_central-1-3_DAPI',
 'feat_moments_central-2-0_DAPI',
 'feat_moments_central-2-1_DAPI',
 'feat_moments_central-2-2_DAPI',
 'feat_moments_central-2-3_DAPI',
 'feat_moments_central-3-0_DAPI',
 'feat_moments_central-3-1_DAPI',
 'feat_moments_central-3-2_DAPI',
 'feat_moments_central-3-3_DAPI',
 'feat_moments_hu-0_DAPI',
 'feat_moments_hu-1_DAPI',
 'feat_moments_hu-2_DAPI',
 'feat_moments_hu-3_DAPI',
 'feat_moments_hu-4_DAPI',
 'feat_moments_hu-5_DAPI',
 'feat_moments_hu-6_DAPI',
 'feat_area_actin',
 'feat_convex_area_actin',
 'feat_eccentricity_actin',
 'feat_equivalent_diameter_actin',
 'feat_euler_number_actin',
 'feat_feret_diameter_max_actin',
 'feat_filled_area_actin',
 'feat_major_axis_length_actin',
 'feat_minor_axis_length_actin',
 'feat_orientation_actin',
 'feat_perimeter_actin',
 'feat_perimeter_crofton_actin',
 'feat_solidity_actin',
 'feat_extent_actin',
 'feat_inertia_tensor-0-0_actin',
 'feat_inertia_tensor-0-1_actin',
 'feat_inertia_tensor-1-0_actin',
 'feat_inertia_tensor-1-1_actin',
 'feat_inertia_tensor_eigvals-0_actin',
 'feat_inertia_tensor_eigvals-1_actin',
 'feat_moments-0-0_actin',
 'feat_moments-0-1_actin',
 'feat_moments-0-2_actin',
 'feat_moments-0-3_actin',
 'feat_moments-1-0_actin',
 'feat_moments-1-1_actin',
 'feat_moments-1-2_actin',
 'feat_moments-1-3_actin',
 'feat_moments-2-0_actin',
 'feat_moments-2-1_actin',
 'feat_moments-2-2_actin',
 'feat_moments-2-3_actin',
 'feat_moments-3-0_actin',
 'feat_moments-3-1_actin',
 'feat_moments-3-2_actin',
 'feat_moments-3-3_actin',
 'feat_moments_central-0-0_actin',
 'feat_moments_central-0-1_actin',
 'feat_moments_central-0-2_actin',
 'feat_moments_central-0-3_actin',
 'feat_moments_central-1-0_actin',
 'feat_moments_central-1-1_actin',
 'feat_moments_central-1-2_actin',
 'feat_moments_central-1-3_actin',
 'feat_moments_central-2-0_actin',
 'feat_moments_central-2-1_actin',
 'feat_moments_central-2-2_actin',
 'feat_moments_central-2-3_actin',
 'feat_moments_central-3-0_actin',
 'feat_moments_central-3-1_actin',
 'feat_moments_central-3-2_actin',
 'feat_moments_central-3-3_actin',
 'feat_moments_hu-0_actin',
 'feat_moments_hu-1_actin',
 'feat_moments_hu-2_actin',
 'feat_moments_hu-3_actin',
 'feat_moments_hu-4_actin',
 'feat_moments_hu-5_actin',
 'feat_moments_hu-6_actin',
 'feat_area_tubulin',
 'feat_convex_area_tubulin',
 'feat_eccentricity_tubulin',
 'feat_equivalent_diameter_tubulin',
 'feat_euler_number_tubulin',
 'feat_feret_diameter_max_tubulin',
 'feat_filled_area_tubulin',
 'feat_major_axis_length_tubulin',
 'feat_minor_axis_length_tubulin',
 'feat_orientation_tubulin',
 'feat_perimeter_tubulin',
 'feat_perimeter_crofton_tubulin',
 'feat_solidity_tubulin',
 'feat_extent_tubulin',
 'feat_inertia_tensor-0-0_tubulin',
 'feat_inertia_tensor-0-1_tubulin',
 'feat_inertia_tensor-1-0_tubulin',
 'feat_inertia_tensor-1-1_tubulin',
 'feat_inertia_tensor_eigvals-0_tubulin',
 'feat_inertia_tensor_eigvals-1_tubulin',
 'feat_moments-0-0_tubulin',
 'feat_moments-0-1_tubulin',
 'feat_moments-0-2_tubulin',
 'feat_moments-0-3_tubulin',
 'feat_moments-1-0_tubulin',
 'feat_moments-1-1_tubulin',
 'feat_moments-1-2_tubulin',
 'feat_moments-1-3_tubulin',
 'feat_moments-2-0_tubulin',
 'feat_moments-2-1_tubulin',
 'feat_moments-2-2_tubulin',
 'feat_moments-2-3_tubulin',
 'feat_moments-3-0_tubulin',
 'feat_moments-3-1_tubulin',
 'feat_moments-3-2_tubulin',
 'feat_moments-3-3_tubulin',
 'feat_moments_central-0-0_tubulin',
 'feat_moments_central-0-1_tubulin',
 'feat_moments_central-0-2_tubulin',
 'feat_moments_central-0-3_tubulin',
 'feat_moments_central-1-0_tubulin',
 'feat_moments_central-1-1_tubulin',
 'feat_moments_central-1-2_tubulin',
 'feat_moments_central-1-3_tubulin',
 'feat_moments_central-2-0_tubulin',
 'feat_moments_central-2-1_tubulin',
 'feat_moments_central-2-2_tubulin',
 'feat_moments_central-2-3_tubulin',
 'feat_moments_central-3-0_tubulin',
 'feat_moments_central-3-1_tubulin',
 'feat_moments_central-3-2_tubulin',
 'feat_moments_central-3-3_tubulin',
 'feat_moments_hu-0_tubulin',
 'feat_moments_hu-1_tubulin',
 'feat_moments_hu-2_tubulin',
 'feat_moments_hu-3_tubulin',
 'feat_moments_hu-4_tubulin',
 'feat_moments_hu-5_tubulin',
 'feat_moments_hu-6_tubulin',
 'feat_mean_DAPI',
 'feat_median_DAPI',
 'feat_max_DAPI',
 'feat_min_DAPI',
 'feat_std_DAPI',
 'feat_mad_DAPI',
 'feat_lower_quartile_DAPI',
 'feat_upper_quartile_DAPI',
 'feat_sum_DAPI',
 'feat_skewness_DAPI',
 'feat_kurtosis_DAPI',
 'feat_bgcorr_mean_DAPI',
 'feat_bgcorr_median_DAPI',
 'feat_bgcorr_max_DAPI',
 'feat_bgcorr_min_DAPI',
 'feat_bgcorr_std_DAPI',
 'feat_bgcorr_mad_DAPI',
 'feat_bgcorr_lower_quartile_DAPI',
 'feat_bgcorr_upper_quartile_DAPI',
 'feat_bgcorr_sum_DAPI',
 'feat_bgcorr_skewness_DAPI',
 'feat_bgcorr_kurtosis_DAPI',
 'feat_edge_mean_DAPI',
 'feat_edge_median_DAPI',
 'feat_edge_max_DAPI',
 'feat_edge_min_DAPI',
 'feat_edge_std_DAPI',
 'feat_edge_mad_DAPI',
 'feat_edge_lower_quartile_DAPI',
 'feat_edge_upper_quartile_DAPI',
 'feat_edge_sum_DAPI',
 'feat_edge_skewness_DAPI',
 'feat_edge_kurtosis_DAPI',
 'feat_bgcorr_edge_mean_DAPI',
 'feat_bgcorr_edge_median_DAPI',
 'feat_bgcorr_edge_max_DAPI',
 'feat_bgcorr_edge_min_DAPI',
 'feat_bgcorr_edge_std_DAPI',
 'feat_bgcorr_edge_mad_DAPI',
 'feat_bgcorr_edge_lower_quartile_DAPI',
 'feat_bgcorr_edge_upper_quartile_DAPI',
 'feat_bgcorr_edge_sum_DAPI',
 'feat_bgcorr_edge_skewness_DAPI',
 'feat_bgcorr_edge_kurtosis_DAPI',
 'feat_combined_mean_DAPI',
 'feat_combined_median_DAPI',
 'feat_combined_max_DAPI',
 'feat_combined_min_DAPI',
 'feat_combined_std_DAPI',
 'feat_combined_mad_DAPI',
 'feat_combined_lower_quartile_DAPI',
 'feat_combined_upper_quartile_DAPI',
 'feat_combined_sum_DAPI',
 'feat_combined_skewness_DAPI',
 'feat_combined_kurtosis_DAPI',
 'feat_combined_bgcorr_mean_DAPI',
 'feat_combined_bgcorr_median_DAPI',
 'feat_combined_bgcorr_max_DAPI',
 'feat_combined_bgcorr_min_DAPI',
 'feat_combined_bgcorr_std_DAPI',
 'feat_combined_bgcorr_mad_DAPI',
 'feat_combined_bgcorr_lower_quartile_DAPI',
 'feat_combined_bgcorr_upper_quartile_DAPI',
 'feat_combined_bgcorr_sum_DAPI',
 'feat_combined_bgcorr_skewness_DAPI',
 'feat_combined_bgcorr_kurtosis_DAPI',
 'feat_combined_edge_mean_DAPI',
 'feat_combined_edge_median_DAPI',
 'feat_combined_edge_max_DAPI',
 'feat_combined_edge_min_DAPI',
 'feat_combined_edge_std_DAPI',
 'feat_combined_edge_mad_DAPI',
 'feat_combined_edge_lower_quartile_DAPI',
 'feat_combined_edge_upper_quartile_DAPI',
 'feat_combined_edge_sum_DAPI',
 'feat_combined_edge_skewness_DAPI',
 'feat_combined_edge_kurtosis_DAPI',
 'feat_combined_bgcorr_edge_mean_DAPI',
 'feat_combined_bgcorr_edge_median_DAPI',
 'feat_combined_bgcorr_edge_max_DAPI',
 'feat_combined_bgcorr_edge_min_DAPI',
 'feat_combined_bgcorr_edge_std_DAPI',
 'feat_combined_bgcorr_edge_mad_DAPI',
 'feat_combined_bgcorr_edge_lower_quartile_DAPI',
 'feat_combined_bgcorr_edge_upper_quartile_DAPI',
 'feat_combined_bgcorr_edge_sum_DAPI',
 'feat_combined_bgcorr_edge_skewness_DAPI',
 'feat_combined_bgcorr_edge_kurtosis_DAPI',
 'feat_mean_actin',
 'feat_median_actin',
 'feat_max_actin',
 'feat_min_actin',
 'feat_std_actin',
 'feat_mad_actin',
 'feat_lower_quartile_actin',
 'feat_upper_quartile_actin',
 'feat_sum_actin',
 'feat_skewness_actin',
 'feat_kurtosis_actin',
 'feat_bgcorr_mean_actin',
 'feat_bgcorr_median_actin',
 'feat_bgcorr_max_actin',
 'feat_bgcorr_min_actin',
 'feat_bgcorr_std_actin',
 'feat_bgcorr_mad_actin',
 'feat_bgcorr_lower_quartile_actin',
 'feat_bgcorr_upper_quartile_actin',
 'feat_bgcorr_sum_actin',
 'feat_bgcorr_skewness_actin',
 'feat_bgcorr_kurtosis_actin',
 'feat_edge_mean_actin',
 'feat_edge_median_actin',
 'feat_edge_max_actin',
 'feat_edge_min_actin',
 'feat_edge_std_actin',
 'feat_edge_mad_actin',
 'feat_edge_lower_quartile_actin',
 'feat_edge_upper_quartile_actin',
 'feat_edge_sum_actin',
 'feat_edge_skewness_actin',
 'feat_edge_kurtosis_actin',
 'feat_bgcorr_edge_mean_actin',
 'feat_bgcorr_edge_median_actin',
 'feat_bgcorr_edge_max_actin',
 'feat_bgcorr_edge_min_actin',
 'feat_bgcorr_edge_std_actin',
 'feat_bgcorr_edge_mad_actin',
 'feat_bgcorr_edge_lower_quartile_actin',
 'feat_bgcorr_edge_upper_quartile_actin',
 'feat_bgcorr_edge_sum_actin',
 'feat_bgcorr_edge_skewness_actin',
 'feat_bgcorr_edge_kurtosis_actin',
 'feat_combined_mean_actin',
 'feat_combined_median_actin',
 'feat_combined_max_actin',
 'feat_combined_min_actin',
 'feat_combined_std_actin',
 'feat_combined_mad_actin',
 'feat_combined_lower_quartile_actin',
 'feat_combined_upper_quartile_actin',
 'feat_combined_sum_actin',
 'feat_combined_skewness_actin',
 'feat_combined_kurtosis_actin',
 'feat_combined_bgcorr_mean_actin',
 'feat_combined_bgcorr_median_actin',
 'feat_combined_bgcorr_max_actin',
 'feat_combined_bgcorr_min_actin',
 'feat_combined_bgcorr_std_actin',
 'feat_combined_bgcorr_mad_actin',
 'feat_combined_bgcorr_lower_quartile_actin',
 'feat_combined_bgcorr_upper_quartile_actin',
 'feat_combined_bgcorr_sum_actin',
 'feat_combined_bgcorr_skewness_actin',
 'feat_combined_bgcorr_kurtosis_actin',
 'feat_combined_edge_mean_actin',
 'feat_combined_edge_median_actin',
 'feat_combined_edge_max_actin',
 'feat_combined_edge_min_actin',
 'feat_combined_edge_std_actin',
 'feat_combined_edge_mad_actin',
 'feat_combined_edge_lower_quartile_actin',
 'feat_combined_edge_upper_quartile_actin',
 'feat_combined_edge_sum_actin',
 'feat_combined_edge_skewness_actin',
 'feat_combined_edge_kurtosis_actin',
 'feat_combined_bgcorr_edge_mean_actin',
 'feat_combined_bgcorr_edge_median_actin',
 'feat_combined_bgcorr_edge_max_actin',
 'feat_combined_bgcorr_edge_min_actin',
 'feat_combined_bgcorr_edge_std_actin',
 'feat_combined_bgcorr_edge_mad_actin',
 'feat_combined_bgcorr_edge_lower_quartile_actin',
 'feat_combined_bgcorr_edge_upper_quartile_actin',
 'feat_combined_bgcorr_edge_sum_actin',
 'feat_combined_bgcorr_edge_skewness_actin',
 'feat_combined_bgcorr_edge_kurtosis_actin',
 'feat_mean_tubulin',
 'feat_median_tubulin',
 'feat_max_tubulin',
 'feat_min_tubulin',
 'feat_std_tubulin',
 'feat_mad_tubulin',
 'feat_lower_quartile_tubulin',
 'feat_upper_quartile_tubulin',
 'feat_sum_tubulin',
 'feat_skewness_tubulin',
 'feat_kurtosis_tubulin',
 'feat_bgcorr_mean_tubulin',
 'feat_bgcorr_median_tubulin',
 'feat_bgcorr_max_tubulin',
 'feat_bgcorr_min_tubulin',
 'feat_bgcorr_std_tubulin',
 'feat_bgcorr_mad_tubulin',
 'feat_bgcorr_lower_quartile_tubulin',
 'feat_bgcorr_upper_quartile_tubulin',
 'feat_bgcorr_sum_tubulin',
 'feat_bgcorr_skewness_tubulin',
 'feat_bgcorr_kurtosis_tubulin',
 'feat_edge_mean_tubulin',
 'feat_edge_median_tubulin',
 'feat_edge_max_tubulin',
 'feat_edge_min_tubulin',
 'feat_edge_std_tubulin',
 'feat_edge_mad_tubulin',
 'feat_edge_lower_quartile_tubulin',
 'feat_edge_upper_quartile_tubulin',
 'feat_edge_sum_tubulin',
 'feat_edge_skewness_tubulin',
 'feat_edge_kurtosis_tubulin',
 'feat_bgcorr_edge_mean_tubulin',
 'feat_bgcorr_edge_median_tubulin',
 'feat_bgcorr_edge_max_tubulin',
 'feat_bgcorr_edge_min_tubulin',
 'feat_bgcorr_edge_std_tubulin',
 'feat_bgcorr_edge_mad_tubulin',
 'feat_bgcorr_edge_lower_quartile_tubulin',
 'feat_bgcorr_edge_upper_quartile_tubulin',
 'feat_bgcorr_edge_sum_tubulin',
 'feat_bgcorr_edge_skewness_tubulin',
 'feat_bgcorr_edge_kurtosis_tubulin',
 'feat_combined_mean_tubulin',
 'feat_combined_median_tubulin',
 'feat_combined_max_tubulin',
 'feat_combined_min_tubulin',
 'feat_combined_std_tubulin',
 'feat_combined_mad_tubulin',
 'feat_combined_lower_quartile_tubulin',
 'feat_combined_upper_quartile_tubulin',
 'feat_combined_sum_tubulin',
 'feat_combined_skewness_tubulin',
 'feat_combined_kurtosis_tubulin',
 'feat_combined_bgcorr_mean_tubulin',
 'feat_combined_bgcorr_median_tubulin',
 'feat_combined_bgcorr_max_tubulin',
 'feat_combined_bgcorr_min_tubulin',
 'feat_combined_bgcorr_std_tubulin',
 'feat_combined_bgcorr_mad_tubulin',
 'feat_combined_bgcorr_lower_quartile_tubulin',
 'feat_combined_bgcorr_upper_quartile_tubulin',
 'feat_combined_bgcorr_sum_tubulin',
 'feat_combined_bgcorr_skewness_tubulin',
 'feat_combined_bgcorr_kurtosis_tubulin',
 'feat_combined_edge_mean_tubulin',
 'feat_combined_edge_median_tubulin',
 'feat_combined_edge_max_tubulin',
 'feat_combined_edge_min_tubulin',
 'feat_combined_edge_std_tubulin',
 'feat_combined_edge_mad_tubulin',
 'feat_combined_edge_lower_quartile_tubulin',
 'feat_combined_edge_upper_quartile_tubulin',
 'feat_combined_edge_sum_tubulin',
 'feat_combined_edge_skewness_tubulin',
 'feat_combined_edge_kurtosis_tubulin',
 'feat_combined_bgcorr_edge_mean_tubulin',
 'feat_combined_bgcorr_edge_median_tubulin',
 'feat_combined_bgcorr_edge_max_tubulin',
 'feat_combined_bgcorr_edge_min_tubulin',
 'feat_combined_bgcorr_edge_std_tubulin',
 'feat_combined_bgcorr_edge_mad_tubulin',
 'feat_combined_bgcorr_edge_lower_quartile_tubulin',
 'feat_combined_bgcorr_edge_upper_quartile_tubulin',
 'feat_combined_bgcorr_edge_sum_tubulin',
 'feat_combined_bgcorr_edge_skewness_tubulin',
 'feat_combined_bgcorr_edge_kurtosis_tubulin',
 'feat_glcm_mean_contrast_3_DAPI',
 'feat_glcm_mean_contrast_5_DAPI',
 'feat_glcm_std_contrast_3_DAPI',
 'feat_glcm_std_contrast_5_DAPI',
 'feat_glcm_mean_dissimilarity_3_DAPI',
 'feat_glcm_mean_dissimilarity_5_DAPI',
 'feat_glcm_std_dissimilarity_3_DAPI',
 'feat_glcm_std_dissimilarity_5_DAPI',
 'feat_glcm_mean_homogeneity_3_DAPI',
 'feat_glcm_mean_homogeneity_5_DAPI',
 'feat_glcm_std_homogeneity_3_DAPI',
 'feat_glcm_std_homogeneity_5_DAPI',
 'feat_glcm_mean_energy_3_DAPI',
 'feat_glcm_mean_energy_5_DAPI',
 'feat_glcm_std_energy_3_DAPI',
 'feat_glcm_std_energy_5_DAPI',
 'feat_glcm_mean_correlation_3_DAPI',
 'feat_glcm_mean_correlation_5_DAPI',
 'feat_glcm_std_correlation_3_DAPI',
 'feat_glcm_std_correlation_5_DAPI',
 'feat_glcm_mean_ASM_3_DAPI',
 'feat_glcm_mean_ASM_5_DAPI',
 'feat_glcm_std_ASM_3_DAPI',
 'feat_glcm_std_ASM_5_DAPI',
 'feat_sobel_mean_DAPI',
 'feat_sobel_std_DAPI',
 'feat_sobel_max_DAPI',
 'feat_sobel_min_DAPI',
 'feat_combined_glcm_mean_contrast_3_DAPI',
 'feat_combined_glcm_mean_contrast_5_DAPI',
 'feat_combined_glcm_std_contrast_3_DAPI',
 'feat_combined_glcm_std_contrast_5_DAPI',
 'feat_combined_glcm_mean_dissimilarity_3_DAPI',
 'feat_combined_glcm_mean_dissimilarity_5_DAPI',
 'feat_combined_glcm_std_dissimilarity_3_DAPI',
 'feat_combined_glcm_std_dissimilarity_5_DAPI',
 'feat_combined_glcm_mean_homogeneity_3_DAPI',
 'feat_combined_glcm_mean_homogeneity_5_DAPI',
 'feat_combined_glcm_std_homogeneity_3_DAPI',
 'feat_combined_glcm_std_homogeneity_5_DAPI',
 'feat_combined_glcm_mean_energy_3_DAPI',
 'feat_combined_glcm_mean_energy_5_DAPI',
 'feat_combined_glcm_std_energy_3_DAPI',
 'feat_combined_glcm_std_energy_5_DAPI',
 'feat_combined_glcm_mean_correlation_3_DAPI',
 'feat_combined_glcm_mean_correlation_5_DAPI',
 'feat_combined_glcm_std_correlation_3_DAPI',
 'feat_combined_glcm_std_correlation_5_DAPI',
 'feat_combined_glcm_mean_ASM_3_DAPI',
 'feat_combined_glcm_mean_ASM_5_DAPI',
 'feat_combined_glcm_std_ASM_3_DAPI',
 'feat_combined_glcm_std_ASM_5_DAPI',
 'feat_combined_sobel_mean_DAPI',
 'feat_combined_sobel_std_DAPI',
 'feat_combined_sobel_max_DAPI',
 'feat_combined_sobel_min_DAPI',
 'feat_glcm_mean_contrast_3_actin',
 'feat_glcm_mean_contrast_5_actin',
 'feat_glcm_std_contrast_3_actin',
 'feat_glcm_std_contrast_5_actin',
 'feat_glcm_mean_dissimilarity_3_actin',
 'feat_glcm_mean_dissimilarity_5_actin',
 'feat_glcm_std_dissimilarity_3_actin',
 'feat_glcm_std_dissimilarity_5_actin',
 'feat_glcm_mean_homogeneity_3_actin',
 'feat_glcm_mean_homogeneity_5_actin',
 'feat_glcm_std_homogeneity_3_actin',
 'feat_glcm_std_homogeneity_5_actin',
 'feat_glcm_mean_energy_3_actin',
 'feat_glcm_mean_energy_5_actin',
 'feat_glcm_std_energy_3_actin',
 'feat_glcm_std_energy_5_actin',
 'feat_glcm_mean_correlation_3_actin',
 'feat_glcm_mean_correlation_5_actin',
 'feat_glcm_std_correlation_3_actin',
 'feat_glcm_std_correlation_5_actin',
 'feat_glcm_mean_ASM_3_actin',
 'feat_glcm_mean_ASM_5_actin',
 'feat_glcm_std_ASM_3_actin',
 'feat_glcm_std_ASM_5_actin',
 'feat_sobel_mean_actin',
 'feat_sobel_std_actin',
 'feat_sobel_max_actin',
 'feat_sobel_min_actin',
 'feat_combined_glcm_mean_contrast_3_actin',
 'feat_combined_glcm_mean_contrast_5_actin',
 'feat_combined_glcm_std_contrast_3_actin',
 'feat_combined_glcm_std_contrast_5_actin',
 'feat_combined_glcm_mean_dissimilarity_3_actin',
 'feat_combined_glcm_mean_dissimilarity_5_actin',
 'feat_combined_glcm_std_dissimilarity_3_actin',
 'feat_combined_glcm_std_dissimilarity_5_actin',
 'feat_combined_glcm_mean_homogeneity_3_actin',
 'feat_combined_glcm_mean_homogeneity_5_actin',
 'feat_combined_glcm_std_homogeneity_3_actin',
 'feat_combined_glcm_std_homogeneity_5_actin',
 'feat_combined_glcm_mean_energy_3_actin',
 'feat_combined_glcm_mean_energy_5_actin',
 'feat_combined_glcm_std_energy_3_actin',

In [13]:
moa_columns = [col for col in labels.columns if col not in ["meta_path"]]
moa_columns

['Unnamed: 0',
 'moa_Actin_disruptors',
 'moa_Aurora_kinase_inhibitors',
 'moa_Cholesterol-lowering',
 'moa_DMSO',
 'moa_DNA_damage',
 'moa_DNA_replication',
 'moa_Eg5_inhibitors',
 'moa_Epithelial',
 'moa_Kinase_inhibitors',
 'moa_Microtubule_destabilizers',
 'moa_Microtubule_stabilizers',
 'moa_Protein_degradation',
 'moa_Protein_synthesis']

In [14]:
labels = labels[moa_columns]
labels

,Unnamed: 0,moa_Actin_disruptors,moa_Aurora_kinase_inhibitors,moa_Cholesterol-lowering,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,512631,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,512632,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,512633,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,512634,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [15]:
data_with_split = data_with_split[feature_columns]

In [16]:
merged_df = pd.merge(data_with_split, labels)

In [17]:
merged_df

,Unnamed: 0,feat_area_combined,feat_convex_area_combined,feat_eccentricity_combined,feat_equivalent_diameter_combined,feat_euler_number_combined,feat_feret_diameter_max_combined,feat_filled_area_combined,feat_major_axis_length_combined,feat_minor_axis_length_combined,...,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0,0.042649,0.041533,0.812408,0.202704,0.0,0.220224,0.042649,0.226154,0.171387,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,1,0.038207,0.035558,0.879849,0.191601,0.0,0.242594,0.038207,0.234046,0.144360,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,2,0.008588,0.008188,0.967887,0.088379,0.0,0.144298,0.008588,0.152873,0.050483,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,3,0.052249,0.048637,0.782962,0.224870,0.0,0.260617,0.052249,0.240008,0.193816,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,4,0.044052,0.042015,0.496559,0.206089,0.0,0.199185,0.044052,0.186832,0.212605,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,512630,0.037973,0.037757,0.906109,0.191000,0.0,0.250089,0.037973,0.251998,0.138088,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,512631,0.021345,0.023419,0.925942,0.142016,0.0,0.207319,0.021345,0.208974,0.102688,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,512632,0.010836,0.010564,0.858048,0.099841,0.0,0.133507,0.010836,0.122368,0.083384,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,512633,0.006055,0.006153,0.888300,0.073473,0.0,0.105631,0.006055,0.098948,0.060928,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,512634,0.006328,0.005847,0.921560,0.075212,0.0,0.105781,0.006328,0.105204,0.054566,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [18]:
merged_df = merged_df.drop(["Unnamed: 0"], axis=1)
merged_df

,feat_area_combined,feat_convex_area_combined,feat_eccentricity_combined,feat_equivalent_diameter_combined,feat_euler_number_combined,feat_feret_diameter_max_combined,feat_filled_area_combined,feat_major_axis_length_combined,feat_minor_axis_length_combined,feat_orientation_combined,...,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0.042649,0.041533,0.812408,0.202704,0.0,0.220224,0.042649,0.226154,0.171387,0.064486,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,0.038207,0.035558,0.879849,0.191601,0.0,0.242594,0.038207,0.234046,0.144360,0.617790,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,0.008588,0.008188,0.967887,0.088379,0.0,0.144298,0.008588,0.152873,0.050483,0.503578,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,0.052249,0.048637,0.782962,0.224870,0.0,0.260617,0.052249,0.240008,0.193816,0.014494,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,0.044052,0.042015,0.496559,0.206089,0.0,0.199185,0.044052,0.186832,0.212605,0.388644,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,0.037973,0.037757,0.906109,0.191000,0.0,0.250089,0.037973,0.251998,0.138088,0.146090,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,0.021345,0.023419,0.925942,0.142016,0.0,0.207319,0.021345,0.208974,0.102688,0.052023,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,0.010836,0.010564,0.858048,0.099841,0.0,0.133507,0.010836,0.122368,0.083384,0.898022,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,0.006055,0.006153,0.888300,0.073473,0.0,0.105631,0.006055,0.098948,0.060928,0.014424,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,0.006328,0.005847,0.921560,0.075212,0.0,0.105781,0.006328,0.105204,0.054566,0.005941,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [19]:
merged_df

,feat_area_combined,feat_convex_area_combined,feat_eccentricity_combined,feat_equivalent_diameter_combined,feat_euler_number_combined,feat_feret_diameter_max_combined,feat_filled_area_combined,feat_major_axis_length_combined,feat_minor_axis_length_combined,feat_orientation_combined,...,moa_DMSO,moa_DNA_damage,moa_DNA_replication,moa_Eg5_inhibitors,moa_Epithelial,moa_Kinase_inhibitors,moa_Microtubule_destabilizers,moa_Microtubule_stabilizers,moa_Protein_degradation,moa_Protein_synthesis
0,0.042649,0.041533,0.812408,0.202704,0.0,0.220224,0.042649,0.226154,0.171387,0.064486,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
1,0.038207,0.035558,0.879849,0.191601,0.0,0.242594,0.038207,0.234046,0.144360,0.617790,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
2,0.008588,0.008188,0.967887,0.088379,0.0,0.144298,0.008588,0.152873,0.050483,0.503578,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
3,0.052249,0.048637,0.782962,0.224870,0.0,0.260617,0.052249,0.240008,0.193816,0.014494,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
4,0.044052,0.042015,0.496559,0.206089,0.0,0.199185,0.044052,0.186832,0.212605,0.388644,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512630,0.037973,0.037757,0.906109,0.191000,0.0,0.250089,0.037973,0.251998,0.138088,0.146090,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512631,0.021345,0.023419,0.925942,0.142016,0.0,0.207319,0.021345,0.208974,0.102688,0.052023,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512632,0.010836,0.010564,0.858048,0.099841,0.0,0.133507,0.010836,0.122368,0.083384,0.898022,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512633,0.006055,0.006153,0.888300,0.073473,0.0,0.105631,0.006055,0.098948,0.060928,0.014424,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1
512634,0.006328,0.005847,0.921560,0.075212,0.0,0.105781,0.006328,0.105204,0.054566,0.005941,...,-1,-1,-1,-1,-1,-1,-1,1,-1,-1

In [20]:
merged_df.to_csv("../data/BBBC021/BBBC021_dataset_complete_one_fold.csv", index=False)